name: Lighthouse CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 1"  # Runs every Monday at 12 PM UTC

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            https://paulwheatcroft.github.io/lighthouse-ci-demo/
            https://paulwheatcroft.github.io/lighthouse-ci-demo/modern.html
            https://paulwheatcroft.github.io/lighthouse-ci-demo/gallery.html
          uploadArtifacts: true
          temporaryPublicStorage: true