name: Lighthouse CI

on:
  push:
    branches:
      - main

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install --prefix ./lighthouse-ci-demo

      - name: Run Lighthouse CI
        run: npx lighthouse-ci --config=lighthouse.config.js